### ISSUE TITLE
[Feature request]: Allow custom ylim value for architectural efficiency plots

### ISSUE THREAD

**Issue by swright87** [intel/p3-analysis-library#10]
### Feature/behavior summary

For cascade plots, the efficiency is always plotted in the range [0, 1]. For architectural efficiency, we're likely to be in the bottom 10% of that range, so for this plots it's useful for the y-axis to run over a much tighter range.

### Solution description

in _cascade.py lines 83 and 181 could be adjusted from [0, 1.1] to a specified value, or to something like [0, max efficiency+10%].

**Comment by swright87** [comment]
A possibly hacky solution is to change line 83 to:
```
ax.set_ylim([0, max(df[eff_column]) * 1.1])
```
and line 181 to:
```
ax.set_ylim([0, max(df[pp_column.replace(" pp", " eff")]) * 1.1])
```

**Comment by Pennycook** [comment]
The `p3.plot.cascade` function returns the axes that were used to plot everything, so you can write something like this to get the same effect:
```python
# Generate a cascade plot
fig = plt.figure(figsize=(6, 5))
cascade, bars, pchart = p3.plot.cascade(df)
cascade.set_ylim([0, 0.2])
bars.set_ylim([0, 0.2])
plt.savefig("cascade.png", bbox_inches="tight")
```

I'd like to hear from @laserkelvin and @yzamora-intel on this too, but I think I have a preference to use an approach like this instead of changing the library behavior.  If we add something like a "ylim" kwarg, we'd be setting the expectation that we may duplicate other matplotlib functionality in future.  If we automatically adjust the y-axis, somebody might easily misread the resulting plot (because we've perhaps foolishly been training people to read the top-right corner as "the best", rather than to read the values on the y-axis...).

@swright87: If we updated the documentation to detail what `p3.plot.cascade` returns, and added an example or two showing how to customize the plots using the returned values, would you consider this issue resolved? Any feedback you have on what the return value of `p3.plot.cascade` _should_ be would also be appreciated; returning the axis objects is sufficient for simple customization like you're requesting here, but maybe we should be providing direct access to even more of the matplotlib internals?  I'm not sure.

**Comment by swright87** [comment]
Your solution works for me and is probably a much neater way of achieving the same effect.
