### ISSUE TITLE
Naming conflict with p3 package

### ISSUE THREAD

**Issue by Pennycook** [intel/p3-analysis-library#48]
### Feature/behavior summary

As discovered by @swright87, there is already a package called p3 available on pypi: https://pypi.org/project/p3/. Although we have no immediate plans to make our package available there, a user may execute `pip install p3` by mistake and download the wrong package.

### Request attributes

- [ ] Would this be a refactor of existing code?
- [ ] Does this proposal require new package dependencies?
- [X] Would this change break backwards compatibility?

### Related issues

N/A

### Solution description

We could ask pypi to remove the conflicting project (which hasn't been updated since 2013) or change the name of this project.

Potential names:
- p3l
- p3al
- p3anlib
- p3analysis
- p3analysislib

### Additional notes

"p3anlib" is probably my favorite of the options I listed above. It's more explicit than the shorter names but isn't too long.

`import p3anlib as p3` as a pattern is similar in complexity to `import pandas as pd`  and `import numpy as np`.

**Comment by swright87** [comment]
+1 for `p3analysis`, I think the `anlib` bit is a little _clunky_.

`p3lib` is taken too, otherwise I would vote for that...!

`p3-analysis-library` is another reasonable shout I think, though a little long. But, it does have the simplicity of matching the folder it installs from/github project name.
